config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
        root to: 'home#index', as: :authenticated_root
   end

    root to: redirect('/users/sign_in')

  
  resources :lectures do
      resources :comments, only: [:create]
  	member do
  		get "add_to_my_lectures"
  		    	delete '/lectures', to: 'lectures#remove'
    end
    collection do
    	get "my_lectures"
    end

    resources :comments, only: [:create]
  end

   resources :colleges, only: [:create, :destroy]
   
  
  resources :posts do
    resources :comments, only: [:create]
  end
  
	devise_for :users, controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lecture.rb
class Lecture < ApplicationRecord
		include Creatable

	  has_many :colleges
	  has_many :users, through: :colleges
	  has_many :comments, as: :commentable

	  validates :subject, presence: true
	  
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: %i[ show edit update destroy remove add_to_my_lectures]

  # GET /lectures or /lectures.json
  def index
    @lectures = Lecture.all
    @current_lectures_id = current_user.lectures.map(&:id)
    @colleges = current_user.colleges.includes(:lecture)
    @college = College.new
    
  end

  # GET /lectures/1 or /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures or /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save

        LectureMailer.on_create_lecture(@lecture, current_user).deliver
        format.html { redirect_to @lecture, notice: "Lecture was successfully created." }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1 or /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        LectureMailer.on_update_lecture(@lecture, current_user).deliver
        format.html { redirect_to @lecture, notice: "Lecture was successfully updated." }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1 or /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: "Lecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lecture_params
      params.require(:lecture).permit(:subject)
    end
  end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% lecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :subject %>
    <%= form.text_field :subject, autofocus: true %> 
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<div style="width: 100%">
  <div style="float: left; width: 50%"> <table>
  <thead>
    <tr>
      <th>Lecture ID</th>
      <th>Subject</th>
      <th>Created_At</th>
      <th colspan="4"> Action </th>
    </tr>
  </thead>

  <tbody> 
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.id %></td>
        <td><%= lecture.subject %></td>
        <td><%= lecture.created_time %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td> 
          <% if !@current_lectures_id.include?(lecture.id)%>
            <%= link_to 'Add to My Lectures', lectures_path(lecture_id: lecture.id) %>
          <% end %> 
        </td>
    <% end %>
  </tbody>
</table>

               </div>
                <% if params[:lecture_id] %>
                 <div style="float: right; width: 50%"> 
                   My Form will come here
                   <%= render 'college/form' %>
                 </div>
                 <% end %>
               </div>

<table>
  <thead>
    <tr>
    <th> S.No. </th>
    <th> My Personal Lectures </th>
    <th> Lecture ID </th>
    <th> College Name </th>
    <th> Action </th>
    </tr>
  </thead>
  <tbody>
      <% @colleges.each_with_index do|college, index| %>
      <tr>
        <td><%= index +1 %></td>
        <td><%= college.lecture.subject %></td>
        <td><%= %></td>
        <td><%= college.name %></td>
        <td><%= link_to 'Destroy', college_path(college), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/my_lectures.html.erb
<h1> My Personal Lecture </h1>

<table>
  <thead>
    <tr>
    <th> S.No. </th>
    <th> My Personal Lectures </th>
    <th> Lecture ID </th>
    <th> Action </th>
    </tr>
  </thead>
  <tbody>
      <% current_user.lectures.each do|lecture| %>
      <tr>
        <td><%= current_user.lectures.index(lecture) +1 %></td>
        <td><%= lecture.subject %></td>
        <td><%= lecture.id %></td>
        <td><%= link_to 'Remove', lectures_lecture_path(lecture), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
           <% end %>
  </tbody>
</table>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @lecture.subject %>
</p>

<h2>Comments:</h2>
  <%= render "comments/comment", abc: @lecture %>

<h2>Add Comments:</h2>
  <%= render "comments/form", abc: @lecture %>


<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>