config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
        root to: 'home#index', as: :authenticated_root
   end

    root to: redirect('/users/sign_in')

  
  resources :lectures do
      resources :comments, only: [:create]
  	member do
  		get "add_to_my_lectures"
  		    	delete '/lectures', to: 'lectures#remove'
    end
    collection do
    	get "my_lectures"
    end

    resources :comments, only: [:create]
  end

   resources :colleges, only: [:create, :destroy]
   
  
  resources :posts do
    resources :comments, only: [:create]
  end
  
	devise_for :users, controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

	include Creatable
	belongs_to :user
	validates :content, presence: true
	scope :short_content, lambda {|count| where("LENGTH(content) < #{count}") }
	has_many :comments, as: :commentable
	
	after_save :after_save_method
	after_create :after_create_method
	after_commit :after_commit_method

	 after_initialize do |user|
    puts "You have initialized an object!!!!!!!!!!!!1"
  end

  after_find do |user|
    puts "You have found an object!!!!!!!!!!!1!"
  end
	

	def self.search(search)
		search ? where(["content LIKE ?","%#{search}%"]) : all
	end

	def after_save_method
		puts '-------------------after save model'
	end

	def after_create_method
		puts '-------------------after create model'
	end

	def after_commit_method
		puts '------------------after commit(create post, save post , destroy post)'
	end


	# model ke object ke through call krwate he, object mtlb single single record(not array)
	#it is an instance method, called in posts#index
	def call_method
		"abacd"
	end

	#class method on singel record , means post#show
	#kaise call krwate he- class name(Post) then method name(self_method)- Post.self_method 
	def self.self_method
		"self method is a class method "
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :get_posts, only: [:show, :edit, :update, :destroy]
	after_action :after_method, only: [:show]
	around_action :around_method, only: [:show]


    def index
  	   @posts = current_user.posts.short_content(7).search(params[:search])
  	   
  	   
    end


	def show
		puts '++++++++++++++++++++ inside show'
	end

	def new
		@post = Post.new

	end

	def create
		@post = current_user.posts.new(post_params)

		if @post.save
			PostMailer.on_create_mail(@post).deliver
			redirect_to posts_path
		else
			render :new
		end
	end

	def edit
			
	end

	def update

		if @post.update(post_params)
			PostMailer.on_update_mail(@post).deliver
			redirect_to @post
		else
			render :edit
		end
		
	end

	def destroy
		@post.destroy

		redirect_to posts_path
	end

	private
	def post_params
		params.require(:post).permit(:content)
	end

	def get_posts
		puts '++++++++++++++++++++ before show'
		@post = current_user.posts.find(params[:id])		
	end

	def after_method
		puts '++++++++++++++++++++ after show'
	end

	def around_method
		puts '++++++++++++++++++++ before around show'
		@abcd = 1

		yield

		@abcd += 1
		puts '++++++++++++++++++++ after around show'
	end


	 	
end

app/helpers/posts_helper.rb
module PostsHelper
	def calculation(abc)
		abc.id + 100
	end
end

app/views/posts/_form.html.erb
<%= form_with model: post do |f| %>
	<%= f.label "Post" %>
	<%= f.text_field :content, placeholder: "Enter post here", autofocus: "autofocus" %>
<% end %>

app/views/posts/edit.html.erb
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<%= form_tag posts_path, method: :get do %> 
    <%= label_tag "search for content:"%> 
     <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
<% end %>

<h1>Posts#index</h1>
<h2><%= Post.self_method %></h2>

<table>
  <thead>
    <tr>
      <th>S.No.</th>
      <th>Post ID</th>
      <th>Posts</th>
      <th> Ternary Operator </th>
      <th>called model method </th>
      <th> using helper </th>
      <th>using concern</th>
      <th colspan="2">Action</th>
    </tr>
  </thead>

  <tbody>
	  <% @posts.each do |i| %>
    <tr>
    	<td><%= @posts.index(i) + 1 %></td>
      <td><%= i.id%></td>
      <td><%= link_to i.content, post_path(i) %></td>
      <td><%= i.content.length < 7 ? "< 7 " : " > 7 "%></td>
      <td><%= i.call_method %></td>     <%# instance method call hui he model ke through %>
      <td><%= calculation(i) %></td>
      <td><%= i.created_time %></td>

      <td><%= link_to 'Edit', edit_post_path(i)%></td>
      <td><%= link_to 'Delete', post_path(i), method: :delete, data: { confirm: "Are you sure?" } %></td>
    </tr>
	   <% end %>

     <%= "chocolate".size > 4 ? "More than four characters" : "Less than four characters"%>
  </tbody>
</table>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.call_method %></h1>


<h1><%= @abcd %></h1>

<h1><%= @post.content %></h1>

<h2>Comments:</h2>
  <%= render "comments/comment", abc: @post %>

<h2>Add Comments:</h2>
  <%= render "comments/form", abc: @post %>