config/routes.rb
Rails.application.routes.draw do

  authenticated :user do
        root to: 'home#index', as: :authenticated_root
   end

    root to: redirect('/users/sign_in')

  
  resources :lectures do
      resources :comments, only: [:create]
  	member do
  		get "add_to_my_lectures"
  		    	delete '/lectures', to: 'lectures#remove'
    end
    collection do
    	get "my_lectures"
    end

    resources :comments, only: [:create]
  end

   resources :colleges, only: [:create, :destroy]
   
  
  resources :posts do
    resources :comments, only: [:create]
  end
  
	devise_for :users, controllers: {registrations: 'registrations'}

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Register</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body><br/><br/>
    <% if  user_signed_in? %>
    <%= "Hello #{current_user.username}" %>
    <%= link_to "Edit",   edit_user_registration_path %>
    <%= link_to "All Post", posts_path %>
    <%= link_to "New Post", new_post_path %><br/>
    <%= link_to "New Lecture", new_lecture_path %>
    <%= link_to "All Lectures", lectures_path %>
    <%= link_to "My Lecture", my_lectures_lectures_path %><br/>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
                
    <% else %>
    <%= link_to "Sign Up", new_user_registration_path %>
        <%= link_to "Sign In", new_user_session_path %>

        <% end %>
            

    <% flash.each do |type, msg| %>
       <div>
          <%= msg %>
       </div>
    <% end %>

    <%= yield %>
  </body>
</html>